### ISSUE TITLE
Falta do conteúdo de determinados arquivos

### ISSUE THREAD

**Issue by GiovanniSM20** [VaiNaWeb/Primeiros-passos-na-Web#1]
decidi dar uma olhada no material e ajudar no trabalho e percebi que há falta de conteúdo em determinados arquivos do repositório.

- [x] 1 = desafio
- [ ] 2 = resumo && desafio
- [ ] 6 = aula && desafio && [ ] resumo  
- [ ] 7 = aula && desafio && resumo  
- [ ] 8 = aula && desafio && resumo  
- [ ] 9 = aula && desafio && resumo  
- [ ] 10 = aula && desafio && resumo  
- [ ] 11 = aula && desafio && resumo  
- [ ] 12 = aula && desafio && resumo  
- [ ] 13 = aula && desafio && resumo  
- [ ] 14 = aula && desafio && resumo  
- [ ] 15 = aula && desafio && resumo   
- [ ] 16 = aula && desafio && resumo  
- [ ] 17 = aula && desafio && resumo  
- [ ] 18 = aula && desafio && resumo  
- [ ] 19 = aula && desafio && resumo  
- [ ] 20 = aula && desafio && resumo  
- [ ] 21 = aula && desafio && resumo

**Comment by daliannyvieira** [comment]
É exatamente o que está em construção. Acertou a lista! ;)
