### ISSUE TITLE
Adicionar mais desafios sobre git e github

### ISSUE THREAD

**Issue by daliannyvieira** [VaiNaWeb/primeiros-passos-na-web#2]
Criar novos desafios e adicionar neste arquivo:
https://github.com/VaiNaWeb/primeiros-passos-na-web/blob/master/aulas/aula06/desafios.md

**Comment by Skalldihor** [comment]
Adicionei este https://github.com/VaiNaWeb/primeiros-passos-na-web/pull/5 a estrutura está um pouco diferente, eu adiciono trechos de código e comandos do git no própio desafio.

**Comment by Skalldihor** [comment]
Oi, eu novamente, adicionei https://github.com/VaiNaWeb/primeiros-passos-na-web/pull/6 para falar sobre conflitos. {^_^}

**Comment by drcabral** [comment]
Olá, acabo de adicionar o desafio 5 ao arquivo (PR #7 ), sobre cherry-pick. Segui a mesma linha de desafios do 1 e 2 e coloquei um conteúdo para auxiliar na resolução.
