### ISSUE TITLE
Escrever sobre acessibilidade

### ISSUE THREAD

**Issue by daliannyvieira** [VaiNaWeb/primeiros-passos-na-web#3]
Neste arquivo
https://github.com/VaiNaWeb/primeiros-passos-na-web/blob/master/aulas/aula12/aula.md

**Comment by hi-hi-ray** [comment]
Olá! Eu irei pegar essa issue, ok?

**Comment by hi-hi-ray** [comment]
@daliannyvieira Abri o PR #10
